version: '3.5'

networks:
    back-tier:
        driver: bridge

services:
    nats:
        hostname: nats
        image: nats:1.0
        build:
            context: './nats'
        container_name: nats
        ports:
            - 4222:4222
            - 8222:8222
        restart: always
        networks:
            - back-tier

    api-gateway:
        image: api-gateway:1.0
        build:
            context: './api-gateway'
        container_name: api-gateway
        depends_on:
            - nats
        restart: always
        environment:
            - NODE_ENV=staging
            - API_PORT=6565
            - API_HOST=0.0.0.0
            - HEMERA_LOG_LEVEL=error
            - JAEGER_URL=jaeger
            - NATS_URL=nats://nats:4222
            - NATS_USER=ruser
            - NATS_PW=T0pS3cr3t
        networks:
            - back-tier
        ports:
            - 6565:6565

    address-service:
        image: auth-service:1.0
        build:
            context: './address-service'
        links:
            - nats
        depends_on:
            - nats
        restart: always
        container_name: address-service
        environment:
            - NODE_ENV=staging
            - HEMERA_LOG_LEVEL=debug
            - NATS_URL=nats://nats:4222
            - NATS_USER=ruser
            - NATS_PW=T0pS3cr3t
            - DADATA_TOKEN=${DADATA_TOKEN}
        networks:
            - back-tier
